# Generated by Django 5.1.1 on 2024-11-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyperion', '0002_alter_dbstudent_bootcamp_alter_dbstudent_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('bootcamp', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('portfolio_url', models.CharField(max_length=255)),
                ('completed', models.IntegerField(default=0)),
                ('incomplete', models.IntegerField(default=0)),
                ('resubmitted', models.IntegerField(default=0)),
                ('below_100', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='dbStudent',
        ),
    ]
